FROM node:10-alpine


# définit le dossier 'app' comme dossier de travail
WORKDIR /app

# copie 'package.json' et 'package-lock.json' (si disponible)
COPY package*.json ./

# installe les dépendances du projet
RUN yarn install
RUN yarn global add @vue/cli

# copie les fichiers et dossiers du projet dans le dossier de travail (par exemple : le dossier 'app')
COPY . .

# construit l'app pour la production en la minifiant
#RUN yarn serve
EXPOSE 8080
EXPOSE 8000
CMD ["yarn", "build"]
